import { makeStyles } from '../../theme';

export const useStyles = makeStyles()(theme => ({
    pageWrapper: {
        width: '100%',
        overflow: 'hidden',
        position: 'relative',
    },
    pageContainer: {
        width: '1312px',
        maxWidth: '100%',
        margin: '0 auto',
        padding: '78px 24px 120px 24px',
        boxSizing: 'border-box',
        position: 'relative',
        [theme.breakpoints.down('sm')]: {
            padding: '48px 16px 80px 16px',
        },
        '&::before': {
            content: '""',
            position: 'absolute',
            top: '-40px',
            left: '58%',
            transform: 'translateX(-50%)',
            width: '1100px',
            height: '440px',
            maxWidth: '150%',
            background:
                theme.palette.mode === 'dark'
                    ? 'radial-gradient(ellipse, rgba(35, 86, 174, 0.45) 0%, rgba(255, 255, 255, 0) 60%)'
                    : 'none',
            pointerEvents: 'none',
            zIndex: -1,
        },
    },
    backLink: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'flex-start',
        gap: '8px',
        width: '100%',
        maxWidth: '980px',
        margin: '0 auto 24px auto',
        border: 'none',
        background: 'none',
        padding: 0,
        cursor: 'pointer',
        fontFamily: "'Roboto', sans-serif",
        fontSize: '16px',
        fontWeight: 400,
        color: theme.palette.primary.main,
        '&:hover': {
            color: theme.palette.mode === 'dark' ? '#7ec3f3' : '#006bbc',
        },
    },
    article: {
        width: '100%',
        maxWidth: '980px',
        margin: '0 auto',
        borderRadius: '12px',
        border: `1px solid ${theme.palette.mode === 'dark' ? '#356D9A' : theme.palette.secondary.main}`,
        backgroundColor: 'transparent',
        backgroundImage: 'none',
        boxShadow: 'none',
        overflow: 'hidden',
    },
    heroImage: {
        display: 'block',
        width: '100%',
        height: 'auto',
        aspectRatio: '1280 / 250',
        objectFit: 'cover',
    },
    articleBody: {
        padding: '32px 32px 40px 32px',
        [theme.breakpoints.down('sm')]: {
            padding: '20px 16px 28px 16px',
        },
    },
    postTitle: {
        fontFamily: 'Audiowide, sans-serif',
        fontSize: '28px',
        fontWeight: 400,
        lineHeight: 1.3,
        letterSpacing: '-0.03em',
        color: theme.palette.primary.main,
        marginBottom: '12px',
        [theme.breakpoints.down(769)]: {
            fontSize: '22px',
        },
        [theme.breakpoints.down(481)]: {
            fontSize: '18px',
        },
    },
    postMeta: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: '12px',
        fontFamily: "'Roboto', sans-serif",
        fontSize: '14px',
        fontWeight: 400,
        color: theme.palette.mode === 'dark' ? 'rgba(255, 255, 255, 0.75)' : 'rgba(0, 0, 0, 0.6)',
        marginBottom: '28px',
    },
    postAuthor: {
        fontWeight: 700,
        color: theme.palette.text.primary,
    },
    translatedHint: {
        margin: '0 0 24px 0',
        padding: '10px 16px',
        borderLeft: `4px solid ${theme.palette.secondary.main}`,
        borderRadius: '6px',
        fontFamily: "'Roboto', sans-serif",
        fontSize: '14px',
        fontWeight: 400,
        backgroundColor: theme.palette.mode === 'dark' ? 'rgba(35, 86, 174, 0.12)' : 'rgba(35, 86, 174, 0.06)',
        color: theme.palette.text.primary,
    },
    markdownBody: {
        width: '100%',
        maxWidth: '100%',
        overflowWrap: 'anywhere',
    },
    editLinkRow: {
        marginTop: '32px',
        display: 'flex',
        justifyContent: 'flex-end',
    },
    editLink: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: '6px',
        fontFamily: "'Roboto', sans-serif",
        fontSize: '14px',
        fontWeight: 400,
        textDecoration: 'none',
        color: theme.palette.mode === 'dark' ? 'rgba(255, 255, 255, 0.6)' : 'rgba(0, 0, 0, 0.6)',
        '&:hover': {
            color: theme.palette.primary.main,
        },
    },
    pagination: {
        width: '100%',
        maxWidth: '980px',
        margin: '24px auto 0 auto',
        display: 'flex',
        justifyContent: 'space-between',
        gap: '16px',
    },
    navButton: {
        maxWidth: '48%',
        minHeight: '38px',
        padding: '8px 20px',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        textAlign: 'left',
        fontFamily: "'Roboto', sans-serif",
        fontSize: '14px',
        fontWeight: 400,
        color: '#FFFFFF',
        backgroundColor: theme.palette.mode === 'dark' ? '#245790' : theme.palette.secondary.main,
        transition: 'background-color 0.2s ease',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        '&:hover': {
            backgroundColor: theme.palette.primary.main,
        },
    },
    navButtonNext: {
        textAlign: 'right',
        marginLeft: 'auto',
    },
    message: {
        fontFamily: "'Roboto', sans-serif",
        fontSize: '18px',
        fontWeight: 400,
        color: theme.palette.text.primary,
    },

    // ---- markdown ----
    head: {
        color: theme.palette.primary.main,
        fontSize: '24px',
        fontFamily: 'Audiowide',
        fontWeight: 400,
        textTransform: 'uppercase',
        marginBottom: '20px',
        scrollMarginTop: '100px',
        letterSpacing: '-0.03em',
        display: 'inline-flex',
        width: '100%',
        alignItems: 'flex-start',
        gap: '16px',
        cursor: 'pointer',
        maxWidth: '100%',
        [theme.breakpoints.down(481)]: {
            fontSize: '18px',
        },
    },
    heading: {
        color: theme.palette.primary.main,
        fontSize: '20px',
        fontFamily: 'Audiowide',
        fontWeight: 400,
        textTransform: 'uppercase',
        marginBottom: '20px',
        scrollMarginTop: '100px',
        letterSpacing: '-0.03em',
        display: 'inline-flex',
        alignItems: 'flex-start',
        gap: '16px',
        cursor: 'pointer',
        maxWidth: '100%',
        [theme.breakpoints.down(769)]: {
            fontSize: '18px',
        },
        [theme.breakpoints.down(481)]: {
            fontSize: '16px',
        },
    },
    linkIcon: {
        width: '20px',
        height: '20px',
        marginTop: '8px',
        flexShrink: 0,
    },
    paragraph: {
        marginBottom: '16px',
        fontSize: '18px',
        fontWeight: 400,
        letterSpacing: '0.01em',
        [theme.breakpoints.down(481)]: {
            fontSize: '16px',
        },
    },
    list: {
        marginLeft: '24px',
        marginBottom: '16px',
    },
    listItem: {
        marginBottom: '8px',
    },
    image: {
        maxWidth: '100%',
        height: 'auto',
        margin: '24px 0',
        borderRadius: '8px',
    },
    table: {
        width: '100%',
        maxWidth: '100%',
        borderCollapse: 'collapse',
        margin: '15px 0',
        fontSize: '16px',
        border: `1px solid ${theme.palette.divider}`,
        borderRadius: '8px',
        overflow: 'hidden',
        tableLayout: 'fixed',
        wordBreak: 'break-word',
        overflowWrap: 'anywhere',
        [theme.breakpoints.down(920)]: {
            fontSize: '14px',
            display: 'block',
            overflow: 'auto',
            whiteSpace: 'nowrap',
        },
        [theme.breakpoints.down(481)]: {
            fontSize: '12px',
        },
    },
    tableHead: {
        backgroundColor: theme.palette.mode === 'dark' ? 'rgba(35, 86, 174, 0.1)' : 'rgba(35, 86, 174, 0.05)',
    },
    tableRow: {
        borderBottom: `1px solid ${theme.palette.divider}`,
        '&:last-child': {
            borderBottom: 'none',
        },
    },
    tableHeaderCell: {
        padding: '12px 16px',
        fontWeight: 600,
        textAlign: 'left',
        color: theme.palette.primary.main,
        borderRight: `1px solid ${theme.palette.divider}`,
        wordBreak: 'break-word',
        overflowWrap: 'anywhere',
        '&:last-child': {
            borderRight: 'none',
        },
        [theme.breakpoints.down(481)]: {
            padding: '6px 8px',
            minWidth: '100px',
        },
    },
    tableCell: {
        padding: '12px 16px',
        borderRight: `1px solid ${theme.palette.divider}`,
        wordBreak: 'break-word',
        overflowWrap: 'anywhere',
        display: 'table-cell',
        '&:last-child': {
            borderRight: 'none',
        },
        [theme.breakpoints.down(481)]: {
            padding: '6px 8px',
            minWidth: '100px',
        },
    },
    codeBlockContainer: {
        backgroundColor: theme.palette.secondary.main,
        borderRadius: '8px',
        border: `1px solid ${theme.palette.secondary.main}`,
        margin: '16px 0 24px 0',
        overflow: 'hidden',
    },
    codeBlockContent: {
        padding: '10px 16px',
        margin: 0,
        fontFamily: 'monospace',
        fontSize: '16px',
        color: '#FFF',
        overflowX: 'hidden',
        overflowY: 'hidden',
        whiteSpace: 'pre-wrap',
        wordBreak: 'break-word',
        backgroundColor: theme.palette.secondary.main,
        '& code': {
            fontFamily: 'inherit',
            fontSize: 'inherit',
            color: 'inherit',
        },
        [theme.breakpoints.down(769)]: {
            fontSize: '12px',
        },
    },
    inlineCode: {
        fontFamily: 'monospace',
        fontSize: '0.95em',
        backgroundColor: theme.palette.mode === 'dark' ? 'rgba(35, 86, 174, 0.25)' : 'rgba(35, 86, 174, 0.12)',
        padding: '2px 6px',
        borderRadius: '4px',
        color: theme.palette.text.primary,
    },
    blockquote: {
        margin: '12px 0 16px 0',
        padding: '10px 16px',
        borderLeft: `4px solid ${theme.palette.secondary.main}`,
        backgroundColor: theme.palette.mode === 'dark' ? 'rgba(35, 86, 174, 0.12)' : 'rgba(35, 86, 174, 0.06)',
        borderRadius: '6px',
        color: theme.palette.text.primary,
        '& p': {
            margin: 0,
        },
    },
}));
