import { makeStyles } from '../../theme';

export const useStyles = makeStyles()(theme => ({
    pageWrapper: {
        width: '100%',
        overflow: 'hidden',
        position: 'relative',
    },
    pageContainer: {
        width: '1312px',
        padding: '78px 0px 157px 0px',
        margin: '0 auto',
        position: 'relative',
        [theme.breakpoints.down(1360)]: {
            width: '100%',
            maxWidth: '1312px',
            padding: '78px 24px 157px 24px',
            boxSizing: 'border-box',
        },
        [theme.breakpoints.down('md')]: {
            justifyContent: 'center',
        },
        [theme.breakpoints.down('sm')]: {
            padding: '60px 10px 110px 10px',
        },
        '&::before': {
            content: '""',
            position: 'absolute',
            top: '85%',
            left: '90%',
            transform: 'translate(-50%, -50%)',
            width: '900px',
            height: '900px',
            background:
                theme.palette.mode === 'dark'
                    ? 'radial-gradient(circle, rgba(0, 88, 148, 0.8) 0%, rgba(255, 255, 255, 0) 55%)'
                    : 'radial-gradient(circle, rgba(255, 255, 255, 0.8) 0%, rgba(255, 255, 255, 0) 55%)',
            pointerEvents: 'none',
            zIndex: -1,
            [theme.breakpoints.down('md')]: {
                top: '98%',
                left: '50%',
                width: '800px',
                height: '200px',
                background:
                    theme.palette.mode === 'dark'
                        ? 'radial-gradient(ellipse, rgba(0, 88, 148, 0.2) 0%, rgba(255, 255, 255, 0) 55%)'
                        : 'radial-gradient(circle, rgba(255, 255, 255, 0.8) 0%, rgba(255, 255, 255, 0) 55%)',
            },
        },
    },
    title: {
        width: '100%',
        maxWidth: '1311px',
        textAlign: 'left',
        [theme.breakpoints.down('md')]: {
            textAlign: 'center',
        },
        [theme.breakpoints.down('sm')]: {
            width: 364,
            margin: '0 auto',
            textAlign: 'left',
        },
    },
    subtitle: {
        marginBottom: 44,
        fontSize: '18px',
        color: theme.palette.text.primary,
        textAlign: 'left',
        maxWidth: '684px',
         [theme.breakpoints.down('md')]: {
            textAlign: 'center',
        },
        [theme.breakpoints.down(430)]: {
            fontSize: 16,
            fontWeight: 300,
            width: 364,
            margin: '0 auto',
            marginBottom: 40,
        },
    },
    cardContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '40px',
        flexWrap: 'wrap',
        alignItems: 'center',
        [theme.breakpoints.up(1360)]: {
            alignItems: 'flex-start',
        },
    },
    cardsWrapper: {
        display: 'flex',
        flexWrap: 'wrap',
        rowGap: '40px',
        columnGap: theme.spacing(3),
        justifyContent: 'center',
        [theme.breakpoints.up(1360)]: {
            justifyContent: 'flex-start',
        },
    },
    card: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        height: '537px',
        width: '644px',
        borderRadius: 24,
        padding: 40,
        backgroundColor: 'transparent !important',
        backgroundImage: 'none',
        border: `1px solid ${theme.palette.primary.main}`,
        transition: 'border-color 0.3s',
        [theme.breakpoints.down(1360)]: {
            width: '100%',
            // maxWidth: '644px',
            height: 'auto',
            boxSizing: 'border-box',
        },
         [theme.breakpoints.down('md')]: {
            width: '100%',
            padding: '20px 16px',
        },
        [theme.breakpoints.down(832)]: {
            minWidth: '382px',
            borderRadius: 10,
        },
    },
    linuxCard: {
        display: 'flex',
        flexDirection: 'column',
        height: '654px',
        width: '1312px',
        padding: 40,
        backgroundColor: 'transparent',
        backgroundImage: 'none',
        border: `1px solid ${theme.palette.primary.main}`,
        borderRadius: 24,
        transition: 'border-color 0.3s',
        [theme.breakpoints.down(1360)]: {
            width: '100%',
            minHeight: '600px',
            height: 'auto',
            boxSizing: 'border-box',
        },
        [theme.breakpoints.down(832)]: {
            minWidth: '382px',
            height: '600px',
            padding: '20px 16px',
            boxSizing: 'border-box',
            borderRadius: 10,
        },
    },
    cardHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'start',
    },
    linuxSubHeader: {
        fontSize: 18,
        fontWeight: 400,
        marginBottom: 57,
        maxWidth: 763,
        marginTop: '-30px',
        [theme.breakpoints.down('md')]: {
            fontSize: 16,
            marginTop: 60,
            marginBottom: 20,
            fontWeight: 300,
        },
    },
    cardTitle: {
        fontFamily: 'Audiowide, Roboto, Arial, sans-serif',
        fontWeight: 400,
        fontSize: '32px',
        textTransform: 'uppercase',
        [theme.breakpoints.down('md')]: {
            fontSize: 20,
        },
    },
    cardIcon: {
        fontSize: '32px',
        color: theme.palette.primary.light,
        [theme.breakpoints.down('md')]: {
            width: 'auto',
            height: 48,
        },
    },
    linuxIcon: {
        width: 116,
        height: 116,
        [theme.breakpoints.down('md')]: {
            width: 48,
            height: 48,
        },
    },
    commandBox: {
        backgroundColor: theme.palette.secondary.main,
        padding: '6px 22px 8px 22px',
        position: 'relative',
        width: 790,
        height: 77,
        fontSize: 24,
        borderRadius: theme.shape.borderRadius,
        color: theme.palette.common.white,
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        wordBreak: 'break-all',
        [theme.breakpoints.down(1360)]: {
            width: '100%',
            maxWidth: 790,
            minHeight: 77,
            height: 'auto',
            boxSizing: 'border-box',
        },
        [theme.breakpoints.down(832)]: {
            minWidth: 351,
            height: 40,
            fontSize: 12,
            minHeight: 40,
            padding: '12px 11px',
        },
    },
    copyConfirmation: {
        position: 'absolute',
        top: 18,
        right: -90,
        transition: 'opacity 0.3s',
        background: theme.palette.common.white,
        color: theme.palette.primary.main,
        borderRadius: theme.shape.borderRadius,
        padding: '5px 10px',
    },
    commandBoxText: {
        marginTop: 8,
        [theme.breakpoints.down('md')]: {
            marginTop: 0,
        },
    },
    copyButton: {
        cursor: 'pointer',
        color: theme.palette.primary.light,
        marginLeft: theme.spacing(2),
        width: 32,
        height: 32,
        [theme.breakpoints.down('md')]: {
            width: 24,
            height: 24,
        },
        '&:hover': {
            opacity: 0.7,
        },
        '&:active': {
            transform: 'scale(0.9)',
        }
    },
    hintText: {
        fontSize: '16px',
        color: theme.palette.text.primary,
        marginTop: 32,
        display: 'flex',
        alignItems: 'center',
        opacity: '0.5',
        letterSpacing: 0,
        [theme.breakpoints.down(832)]: {
            marginTop: 20,
            fontSize: '12px',
            width: 351,
            alignItems: 'start',
        },
    },
    imageTextHeader: {
        fontFamily: 'Saira',
        fontWeight: 600,
        fontSize: 24,
        letterSpacing: '-0.03em',
        [theme.breakpoints.down('md')]: {
            fontWeight: 500,
            textAlign: 'center',
        },
    },
    imageText: {
        fontFamily: 'Saira',
        fontWeight: 400,
        color: theme.palette.text.primary,
        fontSize: 18,
        letterSpacing: '-0.03em',
        width: 435,
        [theme.breakpoints.down(832)]: {
            width: '100%',
            fontSize: 16,
            fontWeight: 300,
            minWidth: 351,
            textAlign: 'center',
        },
         [theme.breakpoints.down(450)]: {
            textAlign: 'start',
        },
    },
    alertIcon: {
        height: 18,
        width: 18,
        [theme.breakpoints.down('md')]: {
            height: 12,
            width: 12,
        },
    },
    alertIconWrapper: {
        marginRight: '8px',
        marginTop: '6px',
        [theme.breakpoints.down('md')]: {
            marginRight: '2px',
            marginTop: '2px',
        },
    },
    imageInfoBox: {
        display: 'flex',
        justifyContent: 'space-between',
        marginTop: 67,
        alignItems: 'start',
        [theme.breakpoints.down(832)]: {
            flexDirection: 'column',
            alignItems: 'center',
            marginTop: 40,
            height: 237,
        },
    },
    detailsText: {
        color: theme.palette.text.primary,
        marginBottom: theme.spacing(1),
        display: 'grid',
        gridTemplateColumns: 'auto 1fr',
        columnGap: 43,
        rowGap: 10,
        alignItems: 'baseline',
        fontSize: '18px !important',
        fontWeight: 400,
        letterSpacing: '0em',
        '& .MuiTypography-root': {
            fontSize: '18px !important',
        },
        [theme.breakpoints.down(832)]: {
            fontSize: '12px !important',
            '& .MuiTypography-root': {
                fontSize: '12px !important',
            },
            '& .MuiTypography-root:nth-of-type(even)': {
                textAlign: 'right',
            },
            marginBottom: 0,
            columnGap: 120,
        },
    },
    detailsLabel: {
        fontWeight: 400,
        color: theme.palette.text.primary,
        [theme.breakpoints.down('md')]: {
            opacity: '0.5',
        },
    },
    cardContent: {
        display: 'flex',
        flexDirection: 'column',
        flex: 1,
        justifyContent: 'space-between',
        [theme.breakpoints.down('md')]: {
            gap: 60,
        },
    },
    cardActions: {
        display: 'flex',
        justifyContent: 'space-between',
        gap: 36,
        marginTop: 43,
        [theme.breakpoints.down(832)]: {
            flexDirection: 'column-reverse',
            alignItems: 'center',
            marginTop: 40,
            gap: 20,
        },
    },
    buttonPrimary: {
        borderRadius: '10px !important',
        fontFamily: 'Audiowide, Roboto, Arial, sans-serif !important',
        fontWeight: '400 !important',
        letterSpacing: '-0.03em !important',
        fontSize: '16px !important',
        width: '400px !important',
        height: '60px !important',
        padding: '0 !important',
        [theme.breakpoints.down(832)]: {
            width: '100% !important',
            minWidth: '348px !important',
            height: '44px !important',
            borderRadius: '8px !important',
            fontSize: '16px !important',
        },
    },
    buttonSecondary: {
        borderColor: theme.palette.primary.dark,
        color: theme.palette.text.primary,
        fontFamily: 'Audiowide, Roboto, Arial, sans-serif',
        fontWeight: 400,
        letterSpacing: '-0.03em',
        border: `1px solid ${theme.palette.secondary.main} !important`,
        borderRadius: 10,
        fontSize: '16px',
        width: 128,
        height: 60,
        '&:hover': {
            borderColor: theme.palette.primary.main,
            backgroundColor: `${theme.palette.primary.main}22`,
        },
        [theme.breakpoints.down(832)]: {
            width: '100% !important',
            minWidth: 348,
            height: 44,
            borderRadius: 8,
            fontSize: '16px',
        },
    },
    buttonSecondaryLinux: {
        marginTop: 90,
        color: theme.palette.text.primary,
        fontFamily: 'Audiowide, Roboto, Arial, sans-serif',
        fontWeight: 400,
        letterSpacing: '-0.03em',
        border: `1px solid ${theme.palette.secondary.main} !important`,
        borderRadius: 16,
        fontSize: '16px',
        width: 128,
        height: 80,
        '&:hover': {
            borderColor: theme.palette.primary.main,
            backgroundColor: `${theme.palette.primary.main}22`,
        },
        [theme.breakpoints.down(832)]: {
            width: '100%',
            marginTop: 0,
            minWidth: 350,
            height: 44,
            borderRadius: 8,
            fontSize: '16px',
        },
    },
}));
