import { makeStyles } from '../../theme';

export const useStyles = makeStyles()(theme => ({
    /**
     * The palette hangs near the top, not in the middle: it grows downwards as results come in,
     * and a box that grows around its own centre moves the first result away under the cursor.
     */
    overlay: {
        position: 'fixed',
        inset: 0,
        zIndex: 1400,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'flex-start',
        padding: '10vh 16px 16px',
        background: theme.palette.mode === 'dark' ? 'rgba(2, 12, 24, 0.72)' : 'rgba(12, 30, 52, 0.42)',
        backdropFilter: 'blur(2px)',
        [theme.breakpoints.down('sm')]: {
            padding: '0',
            alignItems: 'stretch',
        },
    },
    panel: {
        boxSizing: 'border-box',
        width: '100%',
        maxWidth: '720px',
        maxHeight: '76vh',
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
        background: theme.custom.surfaces.surface,
        border: `1px solid ${theme.custom.hairline}`,
        borderRadius: `${theme.custom.radius.card}px`,
        boxShadow: theme.custom.elevation.overlay,
        [theme.breakpoints.down('sm')]: {
            maxWidth: 'none',
            maxHeight: 'none',
            height: '100%',
            borderRadius: 0,
            border: 'none',
        },
    },

    inputRow: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        padding: '0 16px',
        height: '60px',
        flex: '0 0 auto',
        borderBottom: `1px solid ${theme.custom.hairline}`,
    },
    inputIcon: {
        display: 'flex',
        color: theme.custom.textSubtle,
        flex: '0 0 auto',
    },
    input: {
        all: 'unset',
        flex: '1 1 auto',
        minWidth: 0,
        height: '100%',
        fontFamily: theme.typography.fontFamily,
        fontSize: '17px',
        color: theme.palette.text.primary,
        '&::placeholder': { color: theme.custom.textSubtle },
    },
    // a 44 px target around a small cross, the same as everywhere else on the site
    clearButton: {
        all: 'unset',
        boxSizing: 'border-box',
        width: `${theme.custom.control.compactHeight}px`,
        height: `${theme.custom.control.compactHeight}px`,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flex: '0 0 auto',
        cursor: 'pointer',
        borderRadius: `${theme.custom.radius.chip}px`,
        color: theme.custom.textSubtle,
        fontSize: '18px',
        lineHeight: 1,
        '&:hover': { color: theme.palette.text.primary, background: theme.custom.surfaces.raised },
        '&:focus-visible': { boxShadow: theme.custom.focusRing },
    },
    escHint: {
        flex: '0 0 auto',
        fontSize: '11px',
        fontWeight: 700,
        letterSpacing: '0.04em',
        color: theme.custom.textSubtle,
        border: `1px solid ${theme.custom.hairline}`,
        borderRadius: `${theme.custom.radius.chip}px`,
        padding: '3px 6px',
        [theme.breakpoints.down('sm')]: { display: 'none' },
    },

    body: {
        flex: '1 1 auto',
        overflowY: 'auto',
        overscrollBehavior: 'contain',
        '&::-webkit-scrollbar': { width: '8px' },
        '&::-webkit-scrollbar-track': { background: 'transparent' },
        '&::-webkit-scrollbar-thumb': {
            background: theme.custom.hairlineStrong,
            borderRadius: `${theme.custom.radius.pill}px`,
        },
    },
    groupLabel: {
        position: 'sticky',
        top: 0,
        zIndex: 1,
        background: theme.custom.surfaces.surface,
        padding: '14px 16px 6px',
        fontSize: theme.custom.reading.caption.fontSize,
        fontWeight: 700,
        textTransform: 'uppercase',
        letterSpacing: '0.04em',
        color: theme.custom.textSubtle,
        display: 'flex',
        justifyContent: 'space-between',
        gap: '8px',
    },

    hit: {
        all: 'unset',
        boxSizing: 'border-box',
        display: 'block',
        width: '100%',
        cursor: 'pointer',
        padding: '10px 16px',
        borderLeft: '2px solid transparent',
        '&:hover': { background: theme.custom.surfaces.raised },
    },
    // the keyboard and the mouse point at the same thing, so they get the same look
    hitActive: {
        background: theme.custom.surfaces.raised,
        borderLeftColor: theme.palette.primary.main,
    },
    hitTitle: {
        fontSize: '15px',
        fontWeight: 600,
        color: theme.palette.text.primary,
        marginBottom: '2px',
        overflowWrap: 'anywhere',
    },
    hitPath: {
        fontSize: '12px',
        color: theme.custom.textSubtle,
        marginBottom: '3px',
        overflowWrap: 'anywhere',
    },
    hitSnippet: {
        fontSize: theme.custom.reading.small.fontSize,
        lineHeight: 1.45,
        color: theme.custom.textMuted,
        display: '-webkit-box',
        WebkitLineClamp: 2,
        WebkitBoxOrient: 'vertical',
        overflow: 'hidden',
    },
    /** what the query matched - the one place in a result that is allowed to be loud */
    mark: {
        background: 'transparent',
        color: theme.palette.primary.main,
        fontWeight: 700,
    },

    message: {
        padding: '28px 16px',
        textAlign: 'center',
        color: theme.custom.textSubtle,
        fontSize: theme.custom.reading.small.fontSize,
    },
    recentRow: {
        all: 'unset',
        boxSizing: 'border-box',
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
        width: '100%',
        cursor: 'pointer',
        padding: '9px 16px',
        fontSize: '14px',
        color: theme.custom.textMuted,
        '&:hover': { background: theme.custom.surfaces.raised, color: theme.palette.text.primary },
    },

    footer: {
        flex: '0 0 auto',
        borderTop: `1px solid ${theme.custom.hairline}`,
        padding: '10px 16px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: '12px',
    },
    footerHints: {
        display: 'flex',
        gap: '14px',
        fontSize: '12px',
        color: theme.custom.textSubtle,
        [theme.breakpoints.down('sm')]: { display: 'none' },
    },
    allButton: {
        all: 'unset',
        cursor: 'pointer',
        fontSize: '13px',
        fontWeight: 600,
        color: theme.palette.primary.main,
        borderRadius: `${theme.custom.radius.chip}px`,
        padding: '4px 6px',
        '&:hover': { textDecoration: 'underline' },
        '&:focus-visible': { boxShadow: theme.custom.focusRing },
    },
}));
